In [87]:
import numpy as np

### Basic Array Creation

# Creatation of List
How to create Lists in python?

In [98]:
a = ["ahmad", "qasim", "mujeeb"]
a

['ahmad', 'qasim', 'mujeeb']

# Type
Accuire type of list in python.

In [99]:
type(a)

list

# Creatation of Arrays
1.Simple array creation

2.Checking array "TYPE"

3.Numeric "TYPE" of array elements

4.Array dim

5.Array Shape

6.Bytes per element

7.BYTES OF MEMORY USED, How many bytes for one array element

8.Total bytes in an Array

In [100]:
#1 
arr = np.array([1,2,3,4,5,6])
print(arr)
#2.
print(type(arr))
#3.
print(arr.dtype)
#4.
print(arr.ndim)
#5.
print(arr.shape)
#6. 
print(arr.itemsize)
#7. 
print(arr.itemsize)
#8. 
print(arr.nbytes)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32
1
(6,)
4
4
24


In [101]:
#decimal Array
decArr=np.array([1.2,1.3,4.6,7,8])
decArr

array([1.2, 1.3, 4.6, 7. , 8. ])

9.Try to assign a float into an int32

10.Use .fill function # fill has the same behavior


In [102]:
#9.
decArr[2]=5
print(decArr)


#10.
decArr.fill(5)
print(decArr)


[1.2 1.3 5.  7.  8. ]
[5. 5. 5. 5. 5.]


11.Add two  arrays

12.Multiple both arrays

13.Use ** operator in array operation

14.Create array from 0.0 to 11.0

15.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

16.Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0

In [103]:
one =np.array([1,2,3,4,5])
two =np.array([7,8,9,0,1])

#11.
print(one + two)

#12.
print(one * two)

#13.
print(one ** two)

#14.
x=np.arange(12.0)
print(x)

c = (2.0 * np.pi)
x*=c
print(x)

#16. 
stepArr= np.arange(1.0,3.0,0.5)
print(stepArr)

[ 8 10 12  4  6]
[ 7 16 27  0  5]
[    1   256 19683     1     5]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 0.          6.28318531 12.56637061 18.84955592 25.13274123 31.41592654
 37.69911184 43.98229715 50.26548246 56.54866776 62.83185307 69.11503838]
[1.  1.5 2.  2.5]


# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [104]:
x = np.array([1,2,3,4,5,6,7,8])
#1.
print(x[1:4])

#2. 
print(x[-4:-1])

#3. 
print(x[:3])

#4.
print(x[-2:])

#5.
print(x[::2])

#6. 
print(x[:-2])

#7. 
print(x)
#Iterable of 2
x[0:2]=[5,6]
print(x)
#Scalar Value
x[3:5]=8
print(x)


#8. 
n = np.array([[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] )
print(n[2:,0::2])


[2 3 4]
[5 6 7]
[1 2 3]
[7 8]
[1 3 5 7]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]
[5 6 3 4 5 6 7 8]
[5 6 3 8 8 6 7 8]
[]


# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

3.Generate an n by n identity array. The default dtype is float64.

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

5.

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

6.
Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum


In [105]:
#6
a = np.arange(-15, 15).reshape(5, 6) ** 2
print("6. array =\n ",a)

6. array =
  [[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]


### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [96]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

# Answer Here

In [97]:
#For loop to add corresponding elements in two lists

# Answer Here