In [5]:
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Q.1
**Statement:** You are working with a retail store that needs to manage its inventory efficiently. They have provided you with a dataset containing information about products, their quantities in stock, and the number of units sold daily for the past week. Total number of products are 5. Your task is to calculate the following:



1.The total sales for each product over the past week.

2.The average daily sales for each product.

3.The product with the highest sales.

4.The product with the lowest sales.

5.The total sales for all products combined.

You are required to use NumPy for efficient data processing and calculations. Write code to solve this inventory management problem.

In [6]:
import numpy as np

# Sample data (replace with your actual data)
product_names = np.array(['Product A', 'Product B', 'Product C', 'Product D', 'Product E'])
quantities_in_stock = np.array([100, 150, 200, 250, 50])

daily_sales_data = np.array([[10, 15, 20, 25, 30, 35, 40],
                             [5, 7, 8, 10, 12, 14, 16],
                             [15, 20, 25, 30, 35, 40, 40],
                             [12, 25, 20, 40, 20, 32, 55],
                             [15, 20, 25, 30, 35, 40, 45]])

# Calculate total sales revenue for each product over the past week
b=np.sum(daily_sales_data, axis=1)
b

# Calculate the total sales revenue for all products combined


array([175,  72, 205, 204, 210])

In [3]:
# Calculate average daily sales for each product
np.mean(daily_sales_data, axis=1)

array([25.        , 10.28571429, 29.28571429, 29.14285714, 30.        ])

In [7]:
# Find the product with the highest and lowest sales
#Highest Sale
np.max(b)


210

In [8]:
#Lowest Sale
np.min(b)


72

In [9]:
# Calculate the total sales revenue for all products combined
np.sum(b)


866

# Q.2
**Statement:** Statement: You are working with a manufacturing plant that produces various components. They have provided you with data on the production rates of five different machines over the past month. Your task is to analyze the performance of these machines by calculating the following metrics:

1.The total production output for each machine over the past month.

2.The average daily production rate for each machine.

3.The machine with the highest total production output.

4.The machine with the lowest total production output.

The overall production efficiency of the plant, which is defined as the ratio of the total production output to the total number of hours worked, and working hour for each day is 2 hours.

In [18]:


# Sample data (replace with your actual data)
m= np.array(['Machine A', 'Machine B', 'Machine C', 'Machine D', 'Machine E'])
m


# Calculate the overall production efficiency of the plant



array(['Machine A', 'Machine B', 'Machine C', 'Machine D', 'Machine E'],
      dtype='<U9')

In [19]:
# Generate random production rates between 100 and 200 for 5 machines and 30 days
p= np.random.randint(100, 200, size=(5, 30))
p


array([[191, 197, 192, 169, 148, 133, 182, 183, 173, 199, 124, 119, 168,
        150, 188, 171, 197, 192, 118, 178, 196, 187, 120, 114, 156, 195,
        184, 105, 151, 103],
       [168, 133, 195, 114, 101, 153, 183, 181, 141, 114, 147, 162, 127,
        162, 159, 191, 174, 147, 107, 157, 175, 108, 168, 108, 123, 129,
        101, 163, 191, 181],
       [153, 137, 144, 128, 181, 139, 125, 118, 119, 122, 141, 131, 129,
        199, 133, 105, 168, 106, 168, 120, 171, 162, 162, 187, 108, 186,
        159, 106, 199, 145],
       [103, 119, 195, 110, 105, 129, 189, 126, 183, 145, 145, 120, 160,
        101, 156, 120, 149, 133, 132, 117, 153, 169, 194, 190, 115, 102,
        159, 145, 115, 178],
       [134, 115, 167, 135, 170, 138, 124, 158, 110, 190, 124, 171, 156,
        151, 151, 193, 156, 169, 156, 195, 103, 181, 188, 137, 173, 119,
        154, 127, 164, 139]])

In [20]:

# Calculate total production output for each machine over the past month
np.sum(p, axis=1)


array([4883, 4463, 4351, 4257, 4548])

In [21]:
# Calculate average daily production rate for each machine
np.mean(p, axis=0)

array([149.8, 140.2, 178.6, 131.2, 141. , 138.4, 160.6, 153.2, 145.2,
       154. , 136.2, 140.6, 148. , 152.6, 157.4, 156. , 168.8, 149.4,
       136.2, 153.4, 159.6, 161.4, 166.4, 147.2, 135. , 146.2, 151.4,
       129.2, 164. , 149.2])

In [22]:

# Find the machine with the highest and lowest total production output
#Highest Production
np.max(p)


199

In [23]:
#Lowest production
np.min(p)

101

In [24]:
# Calculate the overall production efficiency of the plant
overall_efficiency = np.sum(p) / (2 * 30)
overall_efficiency

375.03333333333336

# Q3:

**Statment**
You are working on a project that involves simulating sensor data for a network of 10 sensors over a period of 15 days. Each sensor collects data once per hour. Your task is to generate a NumPy array named sensor_data to represent this simulated sensor data and perform following statistical analysis on it.

Populate the sensor_data array with random floating-point values between 0.0 and 100.0
The generated values should represent sensor readings collected once per hour.

After generating the sensor_data array, perform the following statistical **calculations:**

1.Calculate the mean (average) sensor reading for each sensor over the 15 days.

2.Calculate the standard deviation of sensor readings for each sensor.

3.Calculate the maximum sensor reading for each sensor.

4.Calculate the minimum sensor reading for each sensor.

5.Calculate the overall mean sensor reading for all sensors and all days.

6.Calculate the overall standard deviation of sensor readings for all sensors an

In [43]:
import numpy as np
import sys


# Data Generation Requirements
num_sensors = 10
num_days = 15
hours_per_day = 24
shape = (num_sensors, num_days * hours_per_day)

# Generate Sensor Data
#s= np.random.uniform(0.0, 100.0, shape)
#s
#np.set_printoptions(threshold=sys.maxsize)
#s
arr = np.random.randint(100, size=(10,360))
j = arr.mean(axis=1)
j

array([50.15555556, 47.71944444, 51.23055556, 51.52777778, 48.08888889,
       49.45      , 50.02777778, 49.60277778, 49.96666667, 45.09444444])

In [21]:
#Calculate the mean (average) sensor reading for each sensor over the 15 day

arr = np.random.randint(100, size=(10,360))
d = np.mean(arr, axis=1)
d

array([49.875     , 49.725     , 48.53333333, 49.43333333, 50.49444444,
       49.40277778, 49.73055556, 49.69166667, 51.25277778, 52.01944444])

In [23]:
#Calculate the standard deviation of sensor readings for each sensor.
s = np.std(arr, axis=1)
s

array([29.71902566, 28.34488858, 28.68950641, 29.11463931, 28.40930935,
       28.20946439, 29.24393878, 28.91216464, 28.84739528, 28.02780682])

In [ ]:
#.Calculate the maximum sensor reading for each sensor.


# Q4:

**Statement**: You are tasked with analyzing the exam scores of 30 students in a class over a period of 10 exams. The exam scores are represented as a NumPy, where each row corresponds to a different student, and each column represents their score in a specific exam.

Populate the exam_scores array with random integer values between 50 and 100 to simulate students' exam performance.

After generating the exam_scores array, perform the following tasks:

1.Calculate the average score for each student over the 10 exams.

2.Calculate the standard deviation of scores for each student.

3.Identify students who have consistently performed well, defined as those whose average score is above 85.

4.Identify students who may need additional support, defined as those whose average score is below 50.

Write code to create and populate the exam_scores array and then perform the specified statistical analysis and performance evaluation tasks on the data.





In [ ]:
import numpy as np

# Create the exam_scores array (30 students, 10 exams)
num_students = 30
num_exams = 10

# Populate the exam_scores array with random scores between 50 and 100

# 1. Calculate the average score for each student over the 10 exams

# 2. Calculate the standard deviation of scores for each student

# 3. Identify students who have consistently performed well (average score > 85)

# 4. Identify students who may need additional support (average score < 60)

