# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

**Rule 1:**

In [ ]:
#Rule 1
import numpy as np
a=np.ones((3,5))
b=np.ones((5,))
b.reshape(1,5)
b[np.newaxis, :]
#Rule 2
c=a+b
tmp_b = b.reshape(1, 5)
tmp_b_repeat = tmp_b.repeat(3, axis=0)
c = a + tmp_b_repeat
c


array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

**Rule 2:**

1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [ ]:
#1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
total_sum = np.add.reduce(arr)
print(total_sum)

#2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
total_sum = np.add.accumulate(arr)
print(total_sum)

[5 7 9]
[[1 2 3]
 [5 7 9]]


### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [ ]:
#Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3
a=np.arange(10,80,5)
b=np.arange(5,47,3)
c=np.vstack([a,b])
c

array([[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75],
       [ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44]])

### Now use indexing to select the 5th 7th and 11th columns

In [ ]:
#Now use indexing to select the 5th 7th and 11th columns
c[:,[4,6,10]]

array([[30, 40, 60],
       [17, 23, 35]])

### Select the 2nd row and fourth-last to second-last columns

In [ ]:
#Select the 2nd row and fourth-last to second-last columns
c[1, -4: -1:]

array([35, 38, 41])

### Select 3rd to 3rd last columns skipping every second column

In [4]:
#Select 3rd to 3rd last columns skipping every second column
a=np.arange(10,80,5)
b=np.arange(5,47,3)
c=np.vstack([a,b])
c[:, 2:-2:2]


array([[20, 30, 40, 50, 60],
       [11, 17, 23, 29, 35]])

###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [4]:
#Select 3rd to 3rd last columns skipping every second column but in reverse order
c[:, 2:-2:2]


### We will work with the following array:

In [ ]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Use slicing only to select 3rd and last row along with 2nd and last columns

In [12]:
#Use slicing only to select 3rd and last row along with 2nd and last columns
import numpy as np
a = np.arange(25).reshape(5, 5)
b=a[[2, 4]]
c=b[:, [1, 4]]
c



array([[11, 14],
       [21, 24]])

### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [14]:
#Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]
a = np.arange(25).reshape(5, 5)
a[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [25]:
#Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]
import numpy as np
b = np.arange(25).reshape(5, 5)
b[[1,3,4], 1:4:2]

array([[ 6,  8],
       [16, 18],
       [21, 23]])

### Change the values 1, 10, 19 and 22 in the array to -2

In [38]:
a = np.arange(25).reshape(5, 5)
a[[0,2,3,4],[1,0,4,2]]=-2
a


array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

### Repeat above using boolean indexing

In [39]:
a = np.arange(25).reshape(5, 5)
mask=a[[0,2,3,4],[1,0,4,2]]=-2
a


array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [40]:
#Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]
a = np.arange(25).reshape(5, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Calculating the sum, min and max of all diagonal values

In [41]:
a = np.arange(25).reshape(5, 5)
b=np.array([0,6,12,18,24])
s=b.sum()
s

60

In [42]:
min=b.min()
min

0

In [43]:
max=b.max()
max

24

### Calculate the sum of differences between the 2nd row and 2nd last column

In [49]:
#calculate the sum of differences between the 2nd row and 2nd last column
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
row=a[1,:]
row


array([5, 6, 7, 8, 9])

In [64]:
col=a[:,4]
col

array([ 4,  9, 14, 19, 24])

In [66]:
diff=row-col
diff

array([  1,  -3,  -7, -11, -15])

In [67]:
sum=np.sum(diff)
sum

-35

### Create a new array that is the sum of even rows and odd rows

In [68]:
#Create a new array that is the sum of even rows and odd rows
a = np.arange(25).reshape(5, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
b=a[::2, :]
b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [71]:
c=a[1::2, :]
c

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [77]:
if b.shape[0] > c.shape[0]:
    b = b[:c.shape[0], :]
    sum=b+c
    sum
print(sum)


[[ 5  7  9 11 13]
 [25 27 29 31 33]]


## You are done. Good job!